export { default as Header } from "./UI/Headers"
export { default as ButtonOutlined } from "./UI/ButtonOutlined"
export { default as Hero } from "./UI/Hero"
export { default as RecentPost} from "./UI/RecentPost"
export { default as Blogpost} from "./UI/Blogpost"
export { default as Postmode} from "./UI/Postmode"
export { default as Deatails} from "./UI/Deatails"
